hikari:
  primary:
    jdbc-url: jdbc:mysql://localhost:3306/databases?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  second:
    jdbc-url: jdbc:mysql://localhost:3306/databases2?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456